#' Import StepOne™ qPCR data
#'
#' This function imports qPCR data exported from StepOne™ Software and
#' optionally calculates target quantities based on a standard curve, or
#' calculates target ratios.
#'
#' @param files A list of data files to import (e.g., generated by \code{list.files})
#' @param delim The delimiter used in the data files
#' @param target.ratios (optional) A list of target ratios to calculate, each
#'   specified as two target names separated by a period (e.g., "C.D"). Target
#'   names must match those in the "Target Name" column of exported data.
#' @param fluor.norm (optional) A list of values to subtract from cycle
#'   threshold values for each target, e.g. to normalize for differences in
#'   fluorescence intensity among targets. Target names must match those in the
#'   "Target Name" column of exported data.
#' @param copy.number (optional) A list of the number of copies of the target
#'   locus per cell, used to convert target ratios to cell ratios. Target names
#'   must match those in the "Target Name" column of exported data.
#' @param ploidy (optional) A list of the ploidy of each target, used to convert
#'   target ratios to cell ratios. Target names must match those in the "Target
#'   Name" column of exported data.
#' @param extract (optional) A list of DNA extraction efficiency values for each
#'   target, used to convert target ratios to cell ratios. Target names must
#'   match those in the "Target Name" column of exported data.
#' @return A list with the following named elements:
#'   \describe{
#'     \item{unknowns}{The qPCR data (i.e., CT values) for each target in each sample.}
#'     \item{result}{The target ratios calculated (if any) for each sample}
#'   }
#' @examples
#' # Example data files provided with steponeR package)
#' file1 <- system.file("extdata/steponedata_1.csv", package = "steponeR")
#' file2 <- system.file("extdata/steponedata_2.csv", package = "steponeR")
#'
#' # Load data from files and calculate target ratios
#' files <- list(file1, file2)
#' df <- steponeR(files=files, target.ratios=c("C.Mcap", "D.Mcap"),
#'                fluor.norm=list(C=2.26827, D=0, Mcap=0.84815),
#'                copy.number=list(C=10, D=2, Mcap=1),
#'                ploidy=list(C=1, D=1, Mcap=2),
#'                extract=list(C=0.813, D=0.813, Mcap=0.982))
#'
#' # Raw data for unknowns
#' head(df$unknowns)
#' # Target ratio results
#' head(df$result)
#' @references
#' For more information about the implementation of these calculations and the
#' use of each parameter in calculating cell ratios from qPCR data, see:
#'
#'     Cunning R, Baker AC (2013) Excess algal symbionts increase the susceptibility of reef
#' corals to climate change. Nature Clim Change 3:259-262.
#' \url{http://dx.doi.org/10.1038/nclimate1711}
#'
#'     Mieog JC, van Oppen MJH, Berkelmans R, Stam WT, Olsen JL (2009)
#' Quantification of algal endosymbionts (*Symbiodinium*) in coral tissue using
#' real-time PCR. Mol Ecol Resour 9:74–82.
#' \url{http://dx.doi.org/10.1111/j.1755-0998.2008.02222.x}
#'

steponeR <- function(files, delim=",", target.ratios, fluor.norm,
                     copy.number, ploidy, extract) {
  #require(plyr)
  #require(reshape2)
  if(is.null(files)) stop("No data files specified")
  # Import data from files
  data0 <- lapply(files, function(x) {
    temp <- suppressWarnings(readLines(x))
    linesToSkip <- grep("^Well", temp) - 1
    dat <- data.frame(Filename=basename(x),
                      read.table(text=temp, skip=linesToSkip, header=T, na.strings="Undetermined",
                                 sep=delim))
    dat <- dat[which(dat[, grep("Target", colnames(dat), value=T)]!=""), ] # Omit empty wells using regex
    dat[, grep("Sample", colnames(dat), value=T)] <- as.character(dat[, grep("Sample", colnames(dat), value=T)]) # Convert sample names to character using regex
    dat
  })
  data0 <- plyr::rbind.fill(data0)
  # Change column name C. to CT
  colnames(data0) <- sub(x=colnames(data0), pattern="C.$", replacement="CT")
  # Check and remove NTC wells
  ntc <- data0[which(data0$Task=="NTC"), ]
  if(any(!is.na(ntc$CT))) warning("Template detected in NTC: interpret data with caution")
  data <- droplevels(data0[!rownames(data0) %in% rownames(ntc), ])
  # Check remaining tasks
  tasks <- levels(data$Task)
  # Subset CT and sample metadata
  if("STANDARD" %in% tasks) {
    #data <- data[, grep("Filename|Well|Sample|Target|Task|CT|Quantity", colnames(data), value=TRUE)]
    data <- data[, c("Filename", "Well", "Sample.Name", "Target.Name", "Task", "CT", "Quantity")]
  } else {
    data <- data[, c("Filename", "Well", "Sample.Name", "Target.Name", "Task", "CT")]
  }
  # Remove wells with no target
  notarget <- data[which(data$Target.Name==""), ]
  if(!plyr::empty(notarget)) {
    apply(notarget, 1, function(x) message(paste("Well", x["Well"], "in", x["Filename"], "discarded: no target")))
    data <- data[!rownames(data) %in% rownames(notarget), ]
  }
  # Drop unused levels from data
  data <- droplevels(data)
  # Create unique sample-plate IDs to distinguish samples run on multiple plates
  data$Sample.Plate <- interaction(data$Sample.Name, data$Filename, sep="~")
  # Separate UNKNOWNS from STANDARDS
  unk <- data[which(data$Task=="UNKNOWN"), ]
  # Process STANDARDS
  if("STANDARD" %in% tasks) {
    # Process STANDARDS
    std <- data[which(data$Task=="STANDARD"), ]
    std <- std[, c("Quantity", "CT", names(which(sapply(std[,c("Target.Name", "Sample.Name", "Filename")], function(x) nlevels(factor(x)) > 1))))]
    std.lm <- lm(log10(Quantity) ~ ., data=std)
    # Use standard curves to calculate quantities for unknowns
    if("UNKNOWN" %in% tasks) {
      unk$copies <- 10^predict(std.lm, newdata = unk[, c("CT", "Target.Name", "Filename")])
      copymeans <- dcast(unk, Sample.Plate ~ Target.Name, mean, na.rm=T, value.var="copies")
      colnames(copymeans) <- c(colnames(copymeans)[1], paste(colnames(copymeans)[-1], "copies", sep="."))
    }
  }
  # Calculate mean and sd of technical replicates for each target for each sample run
  if(nrow(unk)!=0) {
    ctmeans <- dcast(unk, Sample.Plate ~ Target.Name, mean, na.rm=T, value.var="CT")  # na.rm=F
    colnames(ctmeans) <- c(colnames(ctmeans)[1], paste(colnames(ctmeans)[-1], "CT.mean", sep="."))
    ctsds <- dcast(unk, Sample.Plate ~ Target.Name, sd, na.rm=T, value.var="CT")
    colnames(ctsds) <- c(colnames(ctsds)[1], paste(colnames(ctsds)[-1], "CT.sd", sep="."))
    techreps <- dcast(unk, Sample.Plate ~ Target.Name, value.var="CT",
                      fun.aggregate = function(x) length(which(!is.na(x))))
    colnames(techreps) <- c(colnames(techreps)[1], paste(colnames(techreps)[-1], "reps", sep="."))

    # Combine CT means, SDs, techreps, quantities
    if(exists("copymeans")) {
      result <- plyr::join_all(list(ctmeans, ctsds, techreps, copymeans), by="Sample.Plate")
    } else {
      result <- plyr::join_all(list(ctmeans, ctsds, techreps), by="Sample.Plate")
    }
    # Split Sample.Plate column into Plate and Sample.Name columns
    result <- cbind(colsplit(as.character(result$Sample.Plate), pattern="~", names=c("Sample.Name", "File.Name")),
                    result[, -1])
    # List targets present in data
    targets <- levels(data$Target.Name)

    # Optional data adjustments
    # Fluorescence normalization
    if(!is.null(fluor.norm)) {
      if(is.list(fluor.norm)) {
        if (any(!names(fluor.norm) %in% targets)) {
          warning(paste(names(fluor.norm)[which(!names(fluor.norm) %in% targets)], "not a valid Target\n"))
        }
        for (fluor in targets) { ### in targets
          result[, paste(fluor, "CT.mean", sep=".")] <- result[, paste(fluor, "CT.mean", sep=".")] - fluor.norm[[fluor]]
        }
      } else {
        stop("fluor.norm must be a list")
      }
    }
    # Target ratios
    if(!is.null(target.ratios)) {
      # Separate numerator and denominator of desired ratios by period
      ratios <- strsplit(target.ratios, split=".", fixed=T)
      # Check that all ratios have length two
      if(any(unlist(lapply(ratios, length))!=2)) {
        warning(paste(target.ratios[which(unlist(lapply(ratios, length))!=2)],
                      "is not a valid target ratio and will be ignored\n"))
        target.ratios <- target.ratios[-which(unlist(lapply(ratios, length))!=2)]
      }
      # Calculate ratios
      valid <- unlist(lapply(ratios, function(r) !any(!sapply(r, function(x) x %in% targets))))
      if (any(valid==F)) warning(paste("Invalid target ratio:", target.ratios[!valid], "\n"))
      for(ratio in target.ratios[valid]) {
        num <- strsplit(ratio, split=".", fixed=T)[[1]][1]
        denom <- strsplit(ratio, split=".", fixed=T)[[1]][2]
        result[, ratio] <- 2^(result[, paste(denom, "CT.mean", sep=".")] - result[, paste(num, "CT.mean", sep=".")])
      }
    }
    if(!is.null(copy.number)) {
      for(ratio in target.ratios[valid]) {
        num <- strsplit(ratio, split=".", fixed=T)[[1]][1]
        denom <- strsplit(ratio, split=".", fixed=T)[[1]][2]
        cnratio <- copy.number[[num]] / copy.number[[denom]]
        result[, ratio] <- result[, ratio] / cnratio
      }
    }
    if(!is.null(ploidy)) {
      for(ratio in target.ratios[valid]) {
        num <- strsplit(ratio, split=".", fixed=T)[[1]][1]
        denom <- strsplit(ratio, split=".", fixed=T)[[1]][2]
        pratio <- ploidy[[num]] / ploidy[[denom]]
        result[, ratio] <- result[, ratio] / pratio
      }
    }
    if(!is.null(extract)) {
      for(ratio in target.ratios[valid]) {
        num <- strsplit(ratio, split=".", fixed=T)[[1]][1]
        denom <- strsplit(ratio, split=".", fixed=T)[[1]][2]
        eeratio <- extract[[num]] / extract[[denom]]
        result[, ratio] <- result[, ratio] / eeratio
      }
    }
  }
  else {
    result <- NULL
  }
  if("STANDARD" %in% tasks) return(list(standards=list(data=std, lm=std.lm), unknowns=unk, result=result))
  else return(list(unknowns=unk, result=result))
}

